# Magic SM config

dist: 0.0                   # Not used but should be true input
jump_angle: 30              # Angle of the jump
landing_time: 0.5           # Time to drive on landing
imu_thresh: 5.0             # Acceleration threshold to determine if landing or taking off
rampup_time: 1.0
airborne_drive: 0
landing_drive: -100
# For hardcoding purposes only
drive: 52                 # Takeoff speed

sm:
  update_hz: 50
